apiVersion: v1
kind: Service
metadata:
  name: sonar-svc
  labels:
    name: sonar-svc
spec:
  ports:
  - protocol: TCP
    nodePort: 30080
    port: 80
    targetPort: 9000
  selector:
    app: sonar-deployment
  type: NodePort
